add even more words again
timurbuch/gittest pull request #1
Opened 2021-08-17 13:04 UTC by timurbuch

2021-08-17 14:54 UTC, saschacollinet commented
Looks good!

2021-08-17 14:56 UTC, StefanBehring commented
Holy, well done!!

2021-08-17 15:01 UTC, mortaen requested changes
Please consider my changes :)

2021-08-17 15:01 UTC, mortaen commented on neuerordner/neuedatei3.md
>  next one
Looks good, maybe you can make this a heading.
```suggestion
# next one
```

2021-08-17 15:28 UTC, merged

2021-08-20 15:53 UTC, timurbuch commented on neuerordner/neuedatei3.md
>  next one
Yes, you're right 😄